AWSTemplateFormatVersion: 2010-09-09
Description: "Tabla de DynamoDB para el backend de Gestor Personal"

Resources:
  GestorPersonalTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'GestorPersonal'
      AttributeDefinitions:
        - AttributeName: entidad
          AttributeType: S
        - AttributeName: id
          AttributeType: N
      KeySchema:
        - AttributeName: entidad
          KeyType: HASH
        - AttributeName: id
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
